import {StyleSheet} from 'react-native';

import * as constant from '../../../Utils/Constant';

export default StyleSheet.create({
  MainContainer: {
    flex: 1,
    width: '100%',
  },
  notelistContainer: {
    paddingBottom: constant.resW(12),
    paddingHorizontal: constant.resW(4),
    paddingTop: constant.resW(4),
  },
  notelistColumn: {
    justifyContent: 'space-between',
  },
  heroCard: {
    backgroundColor: '#F8FAFF',
    borderColor: '#E2E8F4',
    borderRadius: constant.resW(3),
    borderWidth: 1,
    marginBottom: constant.resW(4),
    paddingHorizontal: constant.resW(4),
    paddingVertical: constant.resW(4),
    shadowColor: '#0F172A',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  heroTitle: {
    color: constant.blackColor,
    fontFamily: constant.typeSemiBold,
    fontSize: constant.font18,
  },
  heroSubtitle: {
    color: constant.baseTextColor,
    fontFamily: constant.typeMedium,
    fontSize: constant.font12,
    lineHeight: constant.resW(4.8),
    marginTop: constant.resW(1),
  },
  noteCardView: {
    borderRadius: constant.resW(3),
    overflow: 'hidden',
    width: '48.5%',
  },
  cardGradient: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F4',
    borderRadius: constant.resW(3),
    borderWidth: 1,
    minHeight: constant.resW(42),
    paddingHorizontal: constant.resW(3),
    paddingTop: constant.resW(3.2),
    paddingBottom: constant.resW(2.8),
    shadowColor: '#0F172A',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  cardAccent: {
    borderRadius: constant.resW(1),
    height: constant.resW(1),
    marginBottom: constant.resW(2.6),
    width: constant.resW(12),
  },
  cardTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  noteIconWrap: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: constant.resW(4),
    height: constant.resW(18),
    justifyContent: 'center',
    width: constant.resW(18),
  },
  noteAssignmentImage: {
    height: constant.resW(12.5),
    width: constant.resW(12.5),
  },
  noteTextBlock: {
    marginTop: constant.resW(3),
  },
  noteDashboardTextStyle: {
    color: constant.blackColor,
    fontFamily: constant.typeSemiBold,
    fontSize: constant.font16,
    lineHeight: constant.resW(6),
  },
  noteSubtitle: {
    color: constant.baseTextColor,
    fontFamily: constant.typeMedium,
    fontSize: constant.font11,
    lineHeight: constant.resW(4.4),
    marginTop: constant.resW(1),
  },
  cardFooter: {
    marginTop: constant.resW(3),
  },
  cardFooterText: {
    color: constant.Blue,
    fontFamily: constant.typeSemiBold,
    fontSize: constant.font12,
  },
  noteactiveDot: {
    fontFamily: constant.typeSemiBold,
    fontSize: constant.font10,
  },
  notedotStyle: {
    alignItems: 'center',
    borderRadius: constant.resW(5),
    justifyContent: 'center',
    paddingHorizontal: constant.resW(2.2),
    paddingVertical: constant.resW(0.8),
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#F8FAFF',
    borderColor: '#E2E8F4',
    borderRadius: constant.resW(3),
    borderWidth: 1,
    marginTop: constant.resW(4),
    paddingHorizontal: constant.resW(4),
    paddingVertical: constant.resW(8),
  },
  emptyStateTitle: {
    color: constant.blackColor,
    fontFamily: constant.typeSemiBold,
    fontSize: constant.font16,
  },
  emptyStateText: {
    color: constant.baseTextColor,
    fontFamily: constant.typeMedium,
    fontSize: constant.font12,
    lineHeight: constant.resW(4.8),
    marginTop: constant.resW(1.2),
    textAlign: 'center',
  },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    justifyContent: 'center',
  },
});
