export const STAFF_CONTENT_VARIANTS = {
  homework: {
    colors: {
      accent: '#5E3BF9',
      accentSoft: '#EDE9FF',
      delete: '#EF4444',
      emptyActionEnd: '#7C3AED',
      emptyActionStart: '#5E3BF9',
      fabEnd: '#7C3AED',
      fabStart: '#5E3BF9',
      headerEnd: '#7C3AED',
      headerStart: '#5E3BF9',
      publish: '#10B981',
      published: '#6B7280',
      screenEnd: '#F4F2FF',
      screenStart: '#F8F7FF',
      uploadAccent: '#5E3BF9',
    },
  },
  notes: {
    colors: {
      accent: '#EC4899',
      accentSoft: '#FCE7F3',
      delete: '#EF4444',
      emptyActionEnd: '#DB2777',
      emptyActionStart: '#EC4899',
      fabEnd: '#DB2777',
      fabStart: '#EC4899',
      headerEnd: '#DB2777',
      headerStart: '#EC4899',
      publish: '#10B981',
      published: '#6B7280',
      screenEnd: '#FDF2F8',
      screenStart: '#FFF7FB',
      uploadAccent: '#EC4899',
    },
  },
  planner: {
    colors: {
      accent: '#8B5CF6',
      accentSoft: '#EDE9FE',
      delete: '#EF4444',
      emptyActionEnd: '#7C3AED',
      emptyActionStart: '#8B5CF6',
      fabEnd: '#7C3AED',
      fabStart: '#8B5CF6',
      headerEnd: '#7C3AED',
      headerStart: '#8B5CF6',
      publish: '#10B981',
      published: '#6B7280',
      screenEnd: '#F0EEFF',
      screenStart: '#F5F3FF',
      uploadAccent: '#8B5CF6',
    },
  },
};

export const STAFF_CONTENT_TEXT = {
  common: {
    add: 'Add',
    delete: 'Delete',
    edit: 'Edit',
    publish: 'Publish',
    published: 'Published',
    update: 'Update',
    upload: 'Add file +',
  },
  homework: {
    emptyDescription: 'No homework has been assigned yet',
    emptyTitle: 'Data not available',
    emptyAction: 'Add Homework',
    listTitle: 'HomeWork',
    addTitle: 'Add HomeWork',
    viewTitle: 'View Homework',
    editTitle: 'Edit HomeWork',
    labels: {
      book: 'Book',
      chapter: 'Chapter (optional)',
      class: 'Class',
      dateOfPublish: 'Date of Publish',
      fromDate: 'From Date',
      section: 'Section',
      subject: 'Subject',
      topic: 'Topic',
    },
    placeholders: {
      book: 'Enter book',
      chapter: 'Enter chapter',
      class: 'Select class',
      section: 'Select section',
      subject: 'Select subject',
      topic: 'Enter topic',
    },
  },
  notes: {
    emptyAction: 'Add Notes',
    emptyDescription: 'Notes are not available yet',
    emptyTitle: 'Data not available',
    listTitle: 'Notes',
    addTitle: 'Add Notes',
    viewTitle: 'View Notes',
    editTitle: 'Edit Notes',
    labels: {
      book: 'Book',
      class: 'Class',
      dateOfPublish: 'Date of Publish',
      fromDate: 'From Date',
      section: 'Section',
      subject: 'Subject',
      topic: 'Topic',
    },
    placeholders: {
      book: 'Enter book',
      class: 'Select class',
      section: 'Select section',
      subject: 'Select subject',
      topic: 'Enter topic',
    },
  },
  planner: {
    emptyAction: 'Add Planner',
    emptyDescription: 'Planner records are not available yet',
    emptyTitle: 'Data not available',
    listTitle: 'Fortnightly Planner',
    addTitle: 'Add Planner',
    viewTitle: 'View Planner',
    editTitle: 'Edit Planner',
    labels: {
      class: 'Class',
      dateOfPublish: 'Date of Publish',
      fromDate: 'From Date',
      section: 'Section',
      subject: 'Subject',
      toDate: 'To Date',
    },
    placeholders: {
      class: 'Select class',
      section: 'Select section',
      subject: 'Select subject',
    },
  },
};

export default {
  STAFF_CONTENT_TEXT,
  STAFF_CONTENT_VARIANTS,
};
