export const STRINGS = {
  appName: "School ERP",
  common: {
    retry: "Retry",
    loading: "Loading...",
    cancel: "Cancel",
    confirm: "Confirm",
    noDataTitle: "Nothing to show yet",
    noDataDescription: "We could not find anything to display right now.",
    unexpectedError: "Something went wrong. Please try again.",
    networkError:
      "We could not reach the server. Please check your internet connection and try again.",
  },
  auth: {
    admissionNumberLabel: "Admission No.",
    admissionNumberPlaceholder: "Type admission number",
    dobLabel: "DOB",
    dobPlaceholder: "Select DOB",
    loginButton: "Log in",
    missingAdmissionNumber: "Please enter your admission number.",
    missingDob: "Please select your date of birth.",
    loginFailed:
      "We could not log you in. Please verify your details and try again.",
  },
  splash: {
    welcome: "Welcome To",
    schoolName: "Satyug Darshan\nVidyalaya",
    poweredBy: "Powered by",
    app: "App",
  },
  home: {
    todayCountLabel: "Today’s Total",
    quickActionsTitle: "Quick actions",
    quickActionsEmpty: "Quick actions are not available right now.",
  },
  updates: {
    title: "Please Update",
    description:
      "You need the latest version of the app to continue using all features.",
    action: "Update",
  },
  attendance: {
    homeTitle: "Attendance",
    addTitle: "Add Attendance",
    viewTitle: "View Attendance",
    sectionTitle: "Students",
    fields: {
      class: "Select Class",
      section: "Select Section",
      date: "Select Date",
      time: "Select Time",
    },
    placeholders: {
      class: "Select class",
      section: "Select section",
      date: "Select date",
      time: "Select time",
    },
    actions: {
      add: {
        title: "Add Attendance",
        description: "Mark attendance for students",
      },
      view: {
        title: "View Attendance",
        description: "Check student attendance records",
      },
    },
    emptyStates: {
      add: {
        title: "No Students to Display",
        description: "Please select class, section and date to load students",
      },
      view: {
        title: "No Students to Display",
        description: "Please select class, section and date to view attendance",
      },
    },
    messages: {
      alreadyMarkedTitle: "Attendance Already Marked",
      alreadyMarkedDescription:
        "Attendance has already been marked for this date.",
      loadStudentsTitle: "Unable to Load Students",
    },
    status: {
      present: "Present",
      absent: "Absent",
    },
    submit: "Submit Attendance",
    successTitle: "Attendance submitted successfully",
    successDescription: "All records have been updated.",
    submitFailed: "We could not submit attendance. Please try again.",
    noClasses: "No classes available",
    noSections: "No sections available",
    unableToLoadStudents: "We could not load the student list.",
  },
  staffProfile: {
    title: "Profile",
    actions: {
      editProfile: "Edit Profile",
      teachingInformation: "Teaching Information",
      changePassword: "Change Password",
      logout: "Logout",
    },
    editProfile: {
      title: "Edit Profile",
      fields: {
        name: "Name",
        email: "Email",
        contact: "Mobile Number",
      },
      placeholders: {
        name: "Enter name",
        email: "Enter email",
        contact: "Enter mobile number",
      },
      updateAction: "Update",
      validation: {
        invalidMobile: "Please enter a valid 10-digit mobile number.",
        missingMobile: "Please enter your mobile number.",
        noChanges: "Please update the mobile number or profile image first.",
        successMessage: "Your profile has been updated successfully.",
        successTitle: "Profile Updated",
      },
      imagePicker: {
        title: "Select Option",
        camera: "Open Camera",
        gallery: "Choose from Gallery",
        close: "Close",
      },
    },
    changePassword: {
      title: "Change Password",
      fields: {
        currentPassword: "Old Password",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
      },
      placeholders: {
        currentPassword: "Enter old password",
        newPassword: "Enter new password",
        confirmPassword: "Re-enter new password",
      },
      updateAction: "Update Password",
      validation: {
        missingFields: "Please enter all required fields",
        minimumLength: "New password must be at least 8 characters long",
        mismatch: "New password and confirm password must match",
        apiMinimumLength: "Password should be minimum 8 characters",
        apiMismatch: "Passwords do not match. Please try again",
        incorrectOldPassword: "Old password is incorrect",
        networkError: "No internet connection",
        timeoutError: "Request timeout, please try again",
        genericError: "Something went wrong. Please try again",
        missingUser: "User details are missing. Please log in again.",
        success: "Password updated successfully",
        successTitle: "Password Updated",
      },
    },
    teachingInformation: {
      title: "Teaching Information",
      labels: {
        class: "Class",
        section: "Section",
        subject: "Subject",
        teacherName: "Teacher Name",
      },
    },
    confirmLogoutTitle: "Log out",
    confirmLogoutDescription: "Are you sure you want to log out?",
    confirmLogoutAction: "Logout",
    contactFallback: "No contact added",
  },
  staffComplaints: {
    listTitle: "Student Complaint",
    addTitle: "Add Complaint",
    actions: {
      add: "Add",
    },
    feedback: {
      classLoadFailed: "Unable to load classes right now.",
      sectionLoadFailed: "Unable to load sections right now.",
      studentsLoadFailed: "Unable to load students right now.",
      missingAdmissionNumber: "Please enter the admission number.",
      missingStudentName: "Please enter the student name.",
      missingClass: "Please select a class.",
      missingSection: "Please select a section.",
      missingComplaintType: "Please select a complaint type.",
      missingComplaint: "Please enter the complaint details.",
      missingUser: "Your session details are missing. Please log in again.",
      submitFailed: "We couldn't submit the complaint. Please try again.",
      submitSuccessMessage: "The complaint has been submitted successfully.",
      submitSuccessTitle: "Complaint Added",
    },
    labels: {
      name: "Name",
      admissionNumber: "Admission no.",
      class: "Class",
      section: "Section",
      complaintType: "Complaint Type",
      description: "Description",
    },
    form: {
      admissionNumber: "Admission no.",
      studentName: "Student Name",
      className: "Class",
      section: "Section",
      complaintType: "Complaint Type",
      complaint: "Complaint",
      placeholders: {
        admissionNumber: "Enter Admission No",
        studentName: "Enter Student Name",
        className: "Select Class",
        section: "Select Section",
        complaintType: "Select Complaint Type",
        complaint: "Enter Complaint",
      },
      complaintTypes: [
        { label: "Academic Issues", value: "academic_issues" },
        { label: "Hostel Facilities", value: "hostel_facilities" },
        { label: "Library Facilities", value: "library_facilities" },
        { label: "Transport", value: "transport" },
        { label: "Food Services", value: "food_services" },
        { label: "Teaching Quality", value: "teaching_quality" },
        { label: "Campus Safety", value: "campus_safety" },
        { label: "Other", value: "other" },
      ],
    },
    status: {
      pending: "Pending",
      approved: "Approved",
    },
  },
};

export default STRINGS;
