import * as constant from "../../../Utils/Constant";
import appBarTheme from "../../../constants/appBarTheme";
import { moderateScale, verticalScale } from "../../../Utils/responsive";

export const attendanceTheme = {
  colors: {
    screenStart: "#EEF4FF",
    screenEnd: "#F6F1FF",
    headerStart: "#255FEF",
    headerEnd: "#5632F2",
    headerText: constant.whiteColor,
    surface: constant.whiteColor,
    surfaceMuted: "#F7F9FC",
    fieldSurface: "#F9FBFF",
    fieldBorder: "#D7DEE9",
    textPrimary: "#27344C",
    textSecondary: "#6E7A92",
    textMuted: "#99A3B5",
    shadow: "#9FB0CC",
    primaryIconStart: "#3E73F6",
    primaryIconEnd: "#4D46F1",
    secondaryIconStart: "#19B7BE",
    secondaryIconEnd: "#1197C7",
    present: "#1FA971",
    presentSurface: "#E9F8F1",
    absent: "#E25563",
    absentSurface: "#FDECEE",
    attendanceListBorder: "#E7EBF4",
    attendanceListCheckbox: "#8D8D8D",
    attendanceListCheckboxActive: "#1F74F2",
    attendanceSummarySurface: "#DCEBFF",
    emptyIconSurface: "#EFF2F8",
    emptyIconStroke: "#98A3B8",
    divider: "#E7EBF4",
    overlay: "rgba(15, 23, 42, 0.22)",
    ripple: "rgba(37, 95, 239, 0.10)",
  },
  gradients: {
    screen: ["#EEF4FF", "#F6F1FF"],
    header: ["#255FEF", "#5632F2"],
    addAction: ["#3E73F6", "#4D46F1"],
    viewAction: ["#19B7BE", "#1197C7"],
  },
  spacing: {
    screenHorizontal: moderateScale(24),
    screenBottom: verticalScale(40),
    contentTop: verticalScale(18),
    sectionGap: verticalScale(22),
    cardPadding: moderateScale(22),
    fieldGap: verticalScale(18),
    fieldLabelGap: verticalScale(10),
    fieldHorizontal: moderateScale(16),
    headerBottom: verticalScale(8),
    sectionTitleTop: verticalScale(8),
    listRowGap: verticalScale(14),
    listRowPaddingVertical: verticalScale(16),
    listRowPaddingHorizontal: moderateScale(18),
    summaryPillHorizontal: moderateScale(22),
    summaryPillVertical: verticalScale(14),
    buttonTop: verticalScale(20),
    modalInset: moderateScale(24),
    modalPadding: moderateScale(18),
    modalOptionPadding: moderateScale(14),
  },
  radius: {
    surface: moderateScale(32),
    field: moderateScale(20),
    actionIcon: moderateScale(54),
    emptyIcon: moderateScale(40),
    statusPill: moderateScale(18),
    studentCheckbox: moderateScale(12),
    button: moderateScale(18),
    modal: moderateScale(24),
  },
  typography: {
    header: appBarTheme.typography.title,
    sectionTitle: constant.font24,
    cardTitle: constant.font22,
    cardDescription: constant.font16,
    fieldLabel: constant.font18,
    fieldValue: constant.font15,
    emptyTitle: constant.font22,
    emptyDescription: constant.font18,
    status: constant.font14,
    button: constant.font18,
    listName: constant.font16,
    summary: constant.font18,
  },
  iconSize: {
    header: appBarTheme.iconSize.back,
    action: moderateScale(44),
    field: moderateScale(22),
    empty: moderateScale(42),
    status: moderateScale(16),
    studentCheckbox: moderateScale(22),
  },
  layout: {
    headerMinHeight: appBarTheme.layout.height,
    headerTopInset: verticalScale(8),
    contentMaxWidthPortrait: moderateScale(820),
    contentMaxWidthLandscape: moderateScale(920),
    actionCardMinHeight: verticalScale(220),
    fieldHeight: verticalScale(58),
    studentsCardMinHeight: verticalScale(320),
    emptyCardMinHeight: verticalScale(320),
    modalMaxHeight: verticalScale(320),
    submitButtonHeight: verticalScale(56),
    summaryPillMinHeight: verticalScale(52),
    studentListRowMinHeight: verticalScale(106),
  },
  borderWidth: {
    field: 1,
    studentCheckbox: 1.5,
    studentListDivider: 1,
  },
  shadow: {
    card: {
      elevation: 0,
      shadowColor: "transparent",
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0,
      shadowRadius: 0,
    },
    actionIcon: {
      elevation: 0,
      shadowColor: "transparent",
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0,
      shadowRadius: 0,
    },
  },
  fontFamily: {
    title: constant.typeBold,
    subtitle: constant.typeRegular,
    section: constant.typeBold,
    label: constant.typeSemiBold,
    value: constant.typeRegular,
    button: constant.typeBold,
    status: constant.typeSemiBold,
  },
};

export default attendanceTheme;
