export const ACADEMIC_VARIANTS = {
  multimedia: {
    colors: {
      accent: '#2563EB',
      accentSoft: '#DBEAFE',
      apply: '#10B981',
      delete: '#EF4444',
      fabEnd: '#1D4ED8',
      fabStart: '#2563EB',
      fieldFill: '#F8FAFF',
      headerEnd: '#1D4ED8',
      headerStart: '#2563EB',
      published: '#6B7280',
      resetEnd: '#1D4ED8',
      resetStart: '#2563EB',
      save: '#F59E0B',
      screenEnd: '#EFF6FF',
      screenStart: '#F8FAFF',
      tableHeader: '#EFF6FF',
    },
  },
  resultGrades: {
    colors: {
      accent: '#D97706',
      accentSoft: '#FEF3C7',
      apply: '#10B981',
      delete: '#EF4444',
      fabEnd: '#B45309',
      fabStart: '#D97706',
      fieldFill: '#FFFDF7',
      headerEnd: '#B45309',
      headerStart: '#D97706',
      published: '#6B7280',
      resetEnd: '#5E3BF9',
      resetStart: '#7C3AED',
      save: '#D97706',
      screenEnd: '#FFFBEB',
      screenStart: '#FFFEF7',
      tableHeader: '#FEF9EC',
    },
  },
  spr: {
    colors: {
      accent: '#10B981',
      accentSoft: '#D1FAE5',
      apply: '#10B981',
      delete: '#EF4444',
      fabEnd: '#059669',
      fabStart: '#10B981',
      fieldFill: '#FFFFFF',
      headerEnd: '#059669',
      headerStart: '#10B981',
      published: '#6B7280',
      resetEnd: '#5E3BF9',
      resetStart: '#7C3AED',
      save: '#F59E0B',
      screenEnd: '#ECFDF5',
      screenStart: '#F8FFF9',
      tableHeader: '#5E3BF9',
    },
  },
  studentPerformance: {
    colors: {
      accent: '#10B981',
      accentSoft: '#D1FAE5',
      apply: '#10B981',
      delete: '#EF4444',
      fabEnd: '#059669',
      fabStart: '#10B981',
      fieldFill: '#F7FBF8',
      headerEnd: '#059669',
      headerStart: '#10B981',
      published: '#6B7280',
      resetEnd: '#5E3BF9',
      resetStart: '#7C3AED',
      save: '#F59E0B',
      screenEnd: '#ECFDF5',
      screenStart: '#F9FFF9',
      tableHeader: '#ECFDF5',
    },
  },
};

export const ACADEMIC_TEXT = {
  common: {
    add: "Add",
    apply: "Apply",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    filterBy: "Filter By",
    marksObtained: "Marks Obtained",
    maxMarks: "Max Marks",
    noData: "No data available",
    play: "Play",
    published: "Published",
    reset: "Reset",
    save: "Save",
    weightage: "Weightage",
  },
  multimedia: {
    listTitle: "MultiMedia",
    metaLabel: "Date of Publish",
    emptyTitle: "Data not available",
  },
  resultGrades: {
    fields: {
      class: "Class",
      examType: "Exam Type",
      grade: "Grade",
      section: "Section",
      stream: "Stream",
      subject: "Subject",
      term: "Term",
    },
    placeholders: {
      class: "Select Class",
      examType: "Select Exam Type",
      grade: "Select Grade",
      section: "Select Section",
      subject: "Select Subject",
      term: "Select Term",
    },
    resultsTitle: "Result And Grades",
    tabs: {
      grades: "Grades",
      results: "Results",
    },
    table: {
      gradeObtained: "Grade Obtained",
      studentName: "Student Name",
    },
  },
  spr: {
    basicInfo: "Basic Information",
    fields: {
      admissionNo: "Admission No",
      areasOfConcern: "Areas of Concern",
      class: "Class",
      classTeacher: "Class Teacher",
      contactNo: "Contact No",
      section: "Section",
      selectDate: "Select Date",
      studentName: "Student Name",
      wardensComment: "Wardens Comment",
    },
    placeholders: {
      admissionNo: "Enter admission no",
      class: "Select Class",
      areasOfConcern: "Enter areas of concern",
      classTeacher: "Enter class teacher",
      contactNo: "Enter contact no",
      section: "Select Section",
      studentName: "Enter student name",
      wardensComment: "Enter comment",
    },
    sectionCards: [
      {
        key: "punctuality",
        options: [
          "Very Regular and Punctual",
          "Good",
          "Average",
          "Below Average",
        ],
        title: "Punctuality And Regularity",
      },
      {
        key: "uniform",
        options: ["Well Dressed", "Good", "Untidy", "Not Wearing Uniform"],
        title: "Uniform",
      },
      {
        key: "homework",
        options: [
          "Always Complete",
          "Partially Complete",
          "Complete",
          "Not Complete",
          "No Response",
        ],
        title: "Homework",
      },
      {
        key: "classwork",
        options: ["Always Complete", "Average", "Not Regular", "Non Attentive"],
        title: "Classwork",
      },
      {
        key: "classInteraction",
        options: ["Regular, Attentive & Sincere", "Average", "No Interaction"],
        title: "Class Interaction",
      },
      {
        key: "discipline",
        options: [
          "Disciplined & Obedient",
          "Good",
          "Average",
          "Needs to Improve",
        ],
        title: "Discipline",
      },
      {
        key: "strength",
        options: [
          "Intellectually Balanced & Socialized",
          "Regular and punctual",
          "Attentive in Class",
          "Follows Instructions",
        ],
        title: "Strength",
      },
    ],
    performanceTitle: "Performance",
    strengthTitle: "Strength",
    subjectColumns: ["Sr. No", "Subject", "Status", "Remarks"],
    subjectRemarksPlaceholder: "Remark",
    subjectStatusPlaceholder: "Status",
    subjects: [
      "English",
      "Hindi",
      "Science",
      "Social Science",
      "Computer",
      "Sanskrit",
      "French",
      "Maths",
    ],
    subjectsTitle: "Subjects",
    titles: {
      add: "Add SPR",
      edit: "Edit SPR",
    },
  },
  sprPerformanceGroups: [
    {
      key: "performanceAcademics",
      label: "Academics",
      options: ["Overall Good/ Academically", "Average", "Needs to Work Hard"],
    },
    {
      key: "performanceSports",
      label: "Sports",
      options: ["Overall Good/ Academically", "Average", "Needs to Work Hard"],
    },
    {
      key: "performanceCultural",
      label: "Cultural",
      options: ["Overall Good/ Academically", "Average", "Needs to Work Hard"],
    },
  ],
  studentPerformance: {
    cardLabels: {
      class: "Class",
      classTeacher: "Class Teacher",
      studentName: "Student Name",
    },
    emptyTitle: "Data not available",
    filters: {
      class: "Class",
      section: "Section",
    },
    listTitle: "Student Performance",
    unpublished: "Unpublished",
  },
};

export default {
  ACADEMIC_TEXT,
  ACADEMIC_VARIANTS,
};
